:- zapSym.

slogan is thing +
[text 	= ""	:string
,notes	= ""	:string
,plan   = ""    :string
,author		:person
,for 		:posint
,num		:posint
].

person is thing + [fname = "" :string, lname ="" :string].

slogan98 is slogan + [for=1998].
slogan99 is slogan + [for=1999].

slogan98 +
[author		=hans
,text		="The slogan level"
,notes 		="We need to create a more positive and larger image to
                outside target communities on the value of our work. The
                Slogan level is a mythical extension to Newell's Knowledge
                level Modelling concept that is the basis of much of modern
                KA. The Slogan level is the level at which we can
                communicate with other communities and funding bodies. The
                'slogan level modelling' approach stresses the need for
                improving our communications skills with other communities."
,plan		="Try to get an article into AI Magazine on the future
                of KA. Create the Slogan Repository to collect slogans. Find
                the best 10 slogans, and award them the The Edward A.
                Feigenbaum Award for Slogan-Level Achievement. Encourage the
                notion of the following up PI (public impact) actions that
                assess the success of the slogan."
].

slogan98 +
[author		= hakar
,text		="Money is knowledge- why doesn't anybody buy it?"
].

slogan98 +
[author		=brian
,text  		="Those who wear pink rabbits never become pregnant."
].

slogan98+
[author		=clare
,text		=" Have a nice day."
].
slogan98+
[author		=yuval
,text		="If you are not acquiring knowledge, you're loosing it."
].          
slogan98+
[author		=gertjan
,text		="Common KADS: knowing what the expert knows."
].
slogan98+
[author		=speel
,text		="Common KADS: The 21st Century Fox."
].
slogan98+
[author		=nigel
,text		="You cannot do it if you can't slogan it."
].
slogan98+
[author		=nigel
,text		="The slogan level is actually inferior to the joke level."
].
slogan98+
[author		=nigel
,text		="The future is ontology."
].
slogan98+
[author		=enrico
,text		="Every tool we do is crashed by you."
].
slogan98+
[author		=tim
,text		="The slogan suppository."
,notes		="What is the appropriate place to store a slogan?"
].
slogan98+
[author		=tim
,text		="'Truth' always changes with experience."
].
slogan98+
[author		=brian
,text		="If I lie, I'm real."
].
slogan98+
[author		=bob
,text		="Ontologies solve your database integration problem."
].
slogan98+
[author		=hans
,text		="Ontologies: getting the value out of your knowledge."
].
slogan98+
[author		=bob
,text		="Tune in to KQML."
].
slogan98+
[author		=bob
,text		="KQML: More that just a radio station to listen to."
].
slogan98+
[author		=joost
,text		="PSMs: Surfing the knowledge level."
].
slogan98+
[author		=joost
,text		="Ontologies: Serving the knowledge level."
].
slogan98+
[author		=hans
,text		="Ontologies: Curing the information overload."
].
slogan98+
[author		=bob
,text		="Ontologies: Surviving the information infarction."
].
slogan98+
[author		=bob
,text		="Solving Problems is our Business."
,notes		="?? reference to the creation of problem solving methods: a
                  current fashion in KA."
].
slogan98+
[author		=anon
,text		="Knowledge: we care."
].
slogan98+
[author		=anon
,text		="If one or more people agree on anything, most of them are
          	  asleep."
].
slogan98+
[author		=alian
,text		="Knowledge burgers."
].
slogan98+
[author		=anon
,text		="As soon as one expert agrees with another, he (sic) is not an
       		  expert."
].
slogan98+
[author		=anon
,text		="AI is what we can't do right now."
].
slogan98+
[author		=anon
,text		="No knowledge capture without representation."
].
slogan98+
[author		=anon
,text		="Resurrect dead experts and dispense with live experts."
,notes		="The creed of the machine learning community."
].
slogan98+
[author		=paul
,text		="Errors are inescapable."
].
slogan98+
[author=rich
,text		="PSMs do IT!"
,notes=		"'Knowledge is power!' is an often heard slogan.
                Problem-Solving Methods (PSMs) are knowledge components that
                operationalize this slogan (at the knowledge level). PSMs
                can significantly reduce the costs of developing knowledge
                systems because they are reusable. Thus, IT systems can be
                built from reusable components instead of being built from
                scratch. Another slogan (whose is it?) is: 'The 20th century
                is the century of code generation. The 21st century will be
                that of code reuse!'. Thus, in order to be prepared for
                2000, we'd better 'think PSM!'."
,plan=		"A short article with the slogan as title will be
                published in the 1997 August issue of the International
                Journal of Human-Computer Studies (in the bulletin section).
                A draft of the article is available. Authors are Richard
                Benjamins, Dieter Fensel and B. Chandrasekaran. A special
                issue for the International Journal of Human-Computer
                Studies devoted to PSMs is planned for the beginning of 1998
                (Guest editors: Richard Benjamins and Dieter Fensel). The
                motivation behind the issue is to present the PSM approach,
                in a coherent way, to a broader public than the KA
                community. The 15th IJCAI (August, 1997, Japan) will host a
                workshop on PSMs organized by Richard Benjamins, B.
                Chandrasekaran, Dieter Fensel, Enrico Motta and Yuval
                Shahar."
].
slogan98+
[author		=anon
,text		="Its on the web! Its obsolete now!"
].
slogan98+
[author		=rich
,text		="Not plug and play but plug and pray."
].
slogan98+
[author		=rich
,text		="Identifying a lack of knowledge is power."
].
slogan98+
[author		=frank
,text		="When something is sufficiently vague, it is at the knowledge."
].
slogan98+
[author		=ed
,text		="Knowledge is power"
,notes		="To be perfectly accurate, Feigenbaum was repeating
                 the 1597 observation of Francis Bacon, Lord of Verulam, and
                 friend to Shakespeare. Feigenbaum's twist on this statement
                 was to argue that heuristic knowledge bases could be used to
                 produce compentant systems. At a time when the AI field was
                 obsessed with algorithms and complete solutions to problems,
                 this was a very radical statement indeed."
].
slogan98+
[author		=yuval
,text		="If you don't acquire medical knowledge you need legal
                  knowledge."
,notes		="A domain specific specialisation of another slogan: If you are not acquiring
                 knowledge, you're loosing it."
].
slogan98+
[author		=gertjan
,text		="Get Layered with CommonKADS!"
,notes		="Needs no explanation."
,plan		="Get the whole KA community on one line."
].

         
slogan98+
[author		=dieter
,text		="Internet is the biggest knowledge-based system we ever saw."
].
slogan98+
[author		=cao
,text		="Knowlegde is not power unless you admit error is fuel."
,notes		="One can not distinguish knowledge from error. When
                 one tries to acquire knowledge, she or he can not avoid
                 domain-specific errors. If knowledge is power, error is
                 fuel.
                 {** J.Reason, Human Error. Cambridge Univ Press. 1990
                  ** Cungen Cao, Looking at the other side of knowledge. To
                    appear in Proceedings of PACES'97.
		 }"
,plan		="Considering a modeling framework in which knowledge
                 and error are (should be 'is') modeled as a whole."
].
slogan98+
[author		=flo
,text		="Looking for a few good ontologies."
,notes		="Very well known to anybody who lives (lived) in the
                 US."
,plan		="Get people to become pragmatic with their research on
                 ontologies. The number one thing we should do when selling
                 the concept to the non-ontology world is stress what are the
                 applications of ontologies and how they can help the
                 knowledge engineer, business users, etc."
].
slogan98+
[author		=edgar
,text		="Where is your knowledge today?"
].
slogan98+
[author		=step
,text		="Empower your level, cope with your knowledge."
,notes		="Specializations, or variations are allowed, such as
                 (the targeted people may changed, depending on the new
                 formed slogan):
                 {** Empower your knowledge, cope with their acquisition.
                  ** Empower your PSMs, cope with the knowledge level. etc.
	         }
                 What does this mean? Nothing! It is just a slogan, thus a
                 few stricking words to coin (or reveal) a need. Some people
                 call this an advertisement. The first slogan is clearly the
                 job undertaken by all knowledge engineers."
].
slogan98+
[author		=aben
,text		="Knowledge Engineers do IT conceptually."
,notes		="IT standing for Information Technology, obviously.
                 This slogan came up during a very creative brown-paper
                 session in one of our project management training workshops."
,plan		="We will continue to use this slogan to bash IT
                 specialists who skipped the knowledge level, and jumped
                 directly from the symbol level to the slogan level. Also, we
                 will try to remain doing IT..."
].
slogan98+
[author		=leif
,text		="Intellectual capital, realizing your companies true value by
          	 finding its hidden brainpower"
].
slogan98+
[author		=anon
,text		="There's too much learning in the learning organization."
].
slogan98+
[author		=gertjan
,text		="Knowledge management, re-engineering for learning."
].
slogan98+
[author		=tim
,text		="Straw men have a funny habit of not burning."
,notes		="Empirically testing idea X is very rare in the KE
                 literature. Often, when we test sophisticated method X
                 against some 'obviously' stupidier approach, the
                 sophisticated approach does not perform much better. Perhaps
                 amongst the complexity of the systems we see around us,
                 there exists a much simpler core that makes up the real
                 source of power in those systems."
,plan		="Encourage the emprical evaluation of KE techniques.
                 For example, hold a special track at the Banff KA worhshop
                 on evaluation KE techniques."
].
slogan98+
[author		=aben
,text		="Being a knowledge engineer is a license for being stupid."
].
slogan98+
[author		=rich
,text		="The less you know, the more you make."
,notes		="To prove this, consider:
                  {** Postulate 1: Knowledge is power; i.e. Knowledge=Power.
                   ** Postulate 2: Time is money; i.e. Time=Money.
		  }
                 Now, as every engineer knows, Work/Time=Power. That is:
                 Work/Money=Knowledge or Money=Work/Knowledge. Observe that
                 as Knowledge approaches zero, Money approaches infinity
                 regardless of the Work done. This theorem lets us explain
                 why knowledge engineers make less money than business
                 executives."
].
slogan98+
[author		=dieter
,text		="Intelligence arises at the border between chaos and order."
,notes		="Providing information access in structured
                 information sorces like databases is simple because of the
                 strong assumptions such representation formalisms make.
                 Providing information access to unstructured information
                 sources like the WWW is boring because of the lack of strong
                 assumptions such representation formalisms make (i.e., not
                 much beyond simple key word matching and human
                 categorization can be provided). Defining an intermediate
                 level that combines comfortable query repsonse of structured
                 information sources with freedom and lazyness of
                 unstructured information sources is clearly the key issue in
                 computer science and AI at the end of the 20tiest century."
,plan		="Promote the (KA)2 initiative."
].

slogan98+
[author		=enric
,text		="Community is Knowledge!"
,notes		="The Knowledge Annotation Initiative of the Knowledge
                 Acquisition Community (KA)2 is an initiative to jointly
                 develop an ontology that models the knowledge acquisition
                 community (its researchers, topics, products, etc.). This
                 ontology will form the basis to annotate WWW documents of
                 the knowledge acquisition community in order to enable
                 intelligent access to these documents. (KA)2 is an open
                 joint-initiative where the participants are actively
                 involved in (i) a distributive ontological engineering
                 process to model the knowledge acquisition community (a
                 domain ontology), and (ii) annotating webpages relevant for
                 the KA community (the instances of the domain ontology).

                 It is the KA community that is the knowledge.

                 Home page of (KA)2 initiative:
                 http://www.aifb.uni-karlsruhe.de/WBS/broker/KA2.html.

                 More information:
                 http://www.iiia.csic.es/~richard/kaw98/benjamins.html."
,plan=		"This slogan is already a fact. The KA community is now
                 knowledge that can be retrieved from the WWW."
].

aben	=person+ [fname="Manfred", lname="Aden", email="Manfred@Unilever.com"].
alian	=person+ [lname="Rappaport", fname="Alan" ].
anon	=person+ [lname="Nonymous", fname="An." ].
bob	=person+ [lname="Wielinga", fname="Bob" ].
brian	=person+ [lname="Gaines", fname="Brian", email="gaines@cpsc.ucalgary.ca" ].
cao	=person+ [lname="Cao", fname="Cungen", email="caocg@iscs.nus.sg"].
clare	=person+ [lname="Morgan", fname="Clare", email="clarem@ozemail.com.au" ].
dieter	=person+ [lname="Fensel", fname="Dieter", email="dfe@aifb.uni-karlsruhe.de" ].
ed	=person+ [lname="Feigenbaum", fname="Edward" ].
edgar	=person+ [lname="Sommer", fname="Edgar", email="es@mindless.com" ].
enric	=person+ [lname="Plaza", fname="Enric", email="enric@iiia.csic.es" ].
enrico	=person+ [lname="Motta", fname="Enrico" ].
flo	=person+ [lname="Tissot", fname="Florence", email="ffillion@kbsi.com" ].
frank	=person+ [lname="van Harmelen", fname="Frank", email="frankh@cs.vu.nl" ].
gertjan	=person+ [lname="van Heijst", fname="Gertjan", email="gvheijst@cibit.hvu.nl" ].
hans    =person+ [lname="Akkerman", fname="Hans"].
joost	=person+ [fname="Joost", lname="Breuker"].
leif	=person+ [lname="Edvinsson", fname="Leif" ].
nigel	=person+ [lname="Shadbolt", fname="Nigel" ].
onto	=person+ [lname="Ontobroker", fname="", email="broker@aifb.uni-karlsruhe.de" ].
paul	=person+ [lname="Compton", fname="Paul", email="compton@cse.unsw.edu.au" ].
rich	=person+ [fname="Richard", lname="Benjamins", email="richard@swi.psy.uva.nl"].
speel	=person+ [lname="Speel", fname="Piet-Hein" ].
step	=person+ [lname="Lapalut", fname="Stephane", email="Stephane.Lapalut@hol.fr" ].
tim	=person+ [lname="Menzies", fname="Tim", email="timm@cse.unsw.edu.au" ].
hakar	=person+ [lname="Hakar", fname="U." ].
yuval	=person+ [lname="Shahar", fname="Yuval" ].
