:- [usual].

*model is 'bathtub- asymmetrical
#1: 1-[tapFlow= -1]
and tub1 is not explicable cause of the 
asymmetrical linke tub1 ++ tapFlow'.

*even  is f.

*uds : tighten,loosen,push,pull,tapFlow,tub1,tub2,plugFlow.

*tapFlow  - tighten.
*tapFlow  + loosen.
*tub1      ++ tapFlow.
*tub2      + tub1.
*tub2      -+ plugFlow.
*plugFlow + push.
*plugFlow - pull.


*rx= [[], [tighten,push]]
,
[tub1 = [20,15]
,tub2= [20,25]
,tapFlow=[20,15]
].

*end.
