* boolean are oneOf = [t,f].
* authors are [groups = [1],persons= [tim ='tim@menzies.com']
	      ,members= [1 = [tim]]].
* boolean are [aa,ll,bb,mm,nn,ii,jj
              ,kk,cc,dd,ee,ff,gg,hh].
* author = 1.
* 1 if aa then cc.
* 2 if cc then dd.
* 3 if dd then not gg.
* 4 if dd then not hh.
* 5 if dd then ii.
* 6 if bb then not cc.
* 7 if not cc then ee.
* 7 if not cc then ff.











