:- op(1004, xfx,   if).
:- op(1003, xfx, then).
:- op(999,   xfy, says).

:- op(1005, xfx,  says).
:- op(1002, xfy,   ror).
:- op(1002, xfy,  rany).
:- op(1002, xfy,    or).
:- op(1002, xfy,   ors).
:- op(1002, xfy,  rors).
 
:- op(1001, xfy,  rand).
:- op(1001, xfy,   and).

:- op(997,  fx,    not).
:- op(996,  fx,     no).
:- op(996,  fx,    yes).
:- op(650,  fx,    all).
:- op(701,  fy,      ?).
:- op(700,  xfx,   ism).
:- op(501,  xfx,    to).
:- op(1,    fx,     ++).
:- op(1,    fx,    +++).
:- op(1,   xfx,      @).