/*\documentclass[twocolumn,global]{svjour}
\usepackage{prod}\begin{document}

\theprogram{{\PROD}} 
\thetocdepth{2} % e.g. 2
\thewp{~menzies/src/pl/prod/prod.tex}
\thetitle{Motivations}
\theauthor{Tim Menzies}
\theinstitute{Lane Department of Computer Science,
             West Virginia Univerity,
             PO Box 6109, Morgantown,
             WV, 26506-6109, USA;\\
             \url{http://tim.menzies.us};
             \url{tim@menzies.us} 
             }
\thereference{WVU, CSEE, AI lab memo \#4, 2003. 
            Available from 
            \url{http://tim.menzies.com/pdf/03prodabout.pdf}}
\theacknowledgement{This research was conducted at West Virginia
  University under NASA contract NCC2-0979. The work was sponsored by
  the NASA Office of Safety and Mission Assurance under the Software
  Assurance Research Program led by the NASA IV\&V Facility.  Reference
  herein to any specific commercial product, process, or service by
  trade name, trademark, manufacturer, or otherwise, does not constitute
  or imply its endorsement by the United States Government.}
\theabstract{{\PROD}, a Prolog documentation system, is motivated
and described.
}
*/

/*




\input{what}
% \input{why} 
\input{how} 
%  \input{who}
\input{prodbugs}
*/

/*
\thepapers{refs}
\theend
\end{document}
*/
