%%%% Knowledge base
%%% Sample project ``eg1''
%<
cocomo       = ga.
label        =  'eg1'.
language     =  prolog.
revl         =  10.
newKsloc     = 100.
adaptedKsloc =   0.
cm           =   0.   % new code
dm           =   0.   % new code
im           =   0.   % new code
aa           =   2.   % basic module search + docu \cite[p24]{boehm00b}
unfm         =   0.4. % somewhat familiar
su           =  30.   % nom=al value \cite[p23]{boehm00b}
at           =   0.
atKprod      =   2.4.
scedPercent  = 100.
pmat         = vl.
pvol         =  l.
ltex         =  l.
%>

