#!/usr/bin/perl -w

sub worker {
    $f=shift();
    open IN,"<$f.pl" or die "can't open $f.pl for input: $!";
    open OUT,">$f.tex" or die "can't open $f.tex for output: $!";    
    while(<IN>) {
	chomp;
	s/^\%\\/\\/;
	s/\/\*//;
	s/\*\///;
	s/^\%\%\%\%(.*)\%<\s*$/\\section{$1}\\begin{Verbatim}/;
	s/^\%\%\%\%(.*)$/\\section{$1}/;
	s/^\%\%\%(.*)\%<\s*$/\\subsection{$1}\\begin{Verbatim}/;
	s/^\%\%\%(.*)$/\\subsection{$1}/;
	s/^\%\%(.*)\%<\s*$/\\subsubsection{$1}\\begin{Verbatim}/;
	s/^\%\%(.*)$/\\subsubsection{$1}/;
	s/\%>/\\end{Verbatim}/;
	s/\%</\\begin{Verbatim}/;
	s/^\%:(.*)/\\end{Verbatim}\n$1\n\\begin{Verbatim}/;
	s/^\%(\S)/$1/;
	print OUT "$_\n";
    }
    close OUT;
    close IN;
}

while ( my $ff = shift(@ARGV) ) {
     print "$ff.tex";
     worker($ff);
    print "!\n";
}
