% epistemological criteria.
causal_model,
component_hypotheses,
correct_device_model,
cost_info,
dependencies_in_model,
device_model,
empirical_associations,
expected_value_database,
expected_values_obtainable,
fault_behavior_constrained,
fault_simulation_rules,
historical_info,
hypothesis_set_dependent,
hypothesis_set_independent,
inference_rules,
knowledge_about_teleology,
knowledge_for_classifying_symptoms,
local_cost_info,
probability_information,
simulation_rules,
statistical_info,
tests_associated_to_hypotheses,
threshold_info,

% environmental criteria
components_easy_replaceable,
components_replaceable,
device_accessible,
device_stable_in_time,
failure_rates_equal,
imprecise_values,
many_initial_normality_observations,
many_initial_observations,
measuring_points_reachable,
measuring_tools,
net_fanout_structure,
reachability_equal,
user_knowledgeable_symptoms,

% assumptions
complete_association_set,
complete_expected_value_database,
complete_fault_model,
exhaustivity_assumption,
hypotheses_can_be_generated,
independence_of_hypotheses,
no_fault_masking,
non_intermittency_assumption,
single_fault_assumption,
