#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
 
what=evenless 
hi() { 
  clear
  tput bold; tput setaf 5
  cat<<-'EOF'
             _ _
____________/ / \_.)_
`.     ,'   @_@_/ ,'|
  `-.-'        , / /|
     `-.____,-'  | ||
              \  \ ||
              |  | \|
             /   \     ,,'
             |    \   //
            /      |  ||
            |    ,-\ //
            |   _\  \||
           (_`-(_____)/  -Shimrod

	EOF
  tput bold; tput setaf 241
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

here="$(dirname $(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd ))"

alias ..='cd ..'
alias ...='cd ../../../'

alias bye="gp; tmux detach"
alias eg="python3.9 eg.py "
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias etch=".  $here/etc/h "
alias gp="git add *;git commit -am save;git push;git status"
alias grep='grep --color=auto'
alias h="history"
alias hello="git pull"
alias ls="ls -G"
alias tmux="tmux -f $here/etc/tmux-conf"
alias vi="vim -u $here/etc/vimrc "
alias vims="vim +PluginInstall +qall"         
alias mds="cd $here/src; ../etc/md *.lua; gp"

doc() {
  mkdir -p $here/docs
  docco -o $here/docs $*
  cp $here/etc/docco.css $here/docs
}

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🥴 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

mytmux() {
  if [ -z "$TMUX" ]; then
    session=$RANDOM
    tmux start-server
    sleep 1
    tmux new-session -d -s $session  

    tmux splitw -h -p 20
    tmux selectp -t 1

    tmux splitw -v  -p 5
    tmux selectp -t 2
    tmux send-keys C-m  "htop"  C-m

    tmux attach-session -t $session
  fi
}
hi
mytmux
