/*\documentclass[twocolumn,global]{svjour}
\usepackage{prod}\begin{document}

\theprogram{CFG} 
\thetocdepth{2} % e.g. 2
\thewp{~menzies/pl/src/prod/config.pl}
\theref{refs.bib}
\thetitle{A simple handler for config files and command line options}
\theauthor{Tim Menzies}
\theinstitute{Lane Department of Computer Science,
             West Virginia University,
             PO Box 6109, Morgantown,
             WV, 26506-6109, USA;\\
             \url{http://tim.menzies.us};
             \url{tim@menzies.us} 
             }
	 
\thereference{_REFERENCE \url{_DOWNLOAD_SITE}}
\theacknowledgement{_ACKNOWLEDGEMENTS}}
\theabstract{_ONE_PARAGRAPH_SUMMARY}
*/

/*
_BODY_OF_DOCUMENT
*/

/*
\theend
\end{document}
*/
