* boolean are oneOf = [t,f].
* authors are [groups = [1],persons= [tim ='tim@menzies.com']
	      ,members= [1 = [tim]]].
* boolean are [aa,ll,bb,cc,dd,ee,ff,gg,hh,ii,jj,kk,ll].

* author = 1.
* 1 if aa then cc.
* 2 if bb then not cc.
* 3 if cc then not ee.
* 4 if cc then not ff.
* 5 if cc then dd.
* 6 if dd then gg.
* 7 if dd then not ll.
* 8 if ii then not jj.
* 9 if hh then jj.
* 10 if jj then not kk.
* 11 if jj then gg.