today(tuesday).

weight(40).

man( fred ).
      is_a( fred, man ).
      likes( fred, apples ).
      author( fred_jones, guide_to_economics ).
      author( 'Fred Smith', 'Economics today', 'Wiley', 1987 ).
author( 'John Smith', 'Economics tomorrow', 'Wiley', 1987 ).

:- op(100,xfx,if),op(95,xfx, then), op(90,xfy,or), op(80,xfy,and), op(70,fy, not).

r(1) if a and b and c or j then d



:- write('hello world!!'). 