quotation(
"Something Went Wrong in Jet Crash, Expert Says"
,"Actual Newspaper Headline"
).
quotation(
"My software never has bugs.  It just develops random features."
,"Anonymous"
).
quotation(
"Rules are made to be broken."
,"Anonymous"
).
quotation(
"Knowledge rests not on truth alone, but upon 
error also","Anonymous"
).
quotation(
"What was the best thing before sliced bread?"
,"Anonymous"
).
quotation(
"You can never successfully determine before
hand which side of the bread to butter.  "
,"Anonymous"
).
quotation(
"People who love sausage and respect the law
should never watch either being made."
,"Anonymous"
).
quotation(
"What garlic is to food, insanity is to art."
,"Anonymous"
).
quotation(
"Bring me into the company of those who seek 
the truth, and deliver me from those who have 
found it."
,"Anonymous"
).
quotation(
"There have been cans of dog food more
splendiferous than South Richmond. Land mines
more tender."
,"Anonymous"
).
quotation(
"I wish to God these calculations had been
executed by steam."
,"Charles Babbage (1792-1871)"
).
quotation("As scarce as truth is, the supply has always
been in excess of the demand."
,"Josh Billings"
).
quotation(
"Is this true, or only clever?"
,"Augustine Birrell"
).
quotation(
"A model is a lie that lets you know the truth."
,"George Box"
).
quotation(
"All models are wrong, but some are useful."
,"George Box"
).
quotation(
"This idea isn't even  false."
,"Neils Bohr"
).
quotation(
"I have seen the truth, and it makes no sense. "
,"G.K. Chesterton"
).
quotation("Man will occasionally stumble over the truth,
but most of the time he will pick himself up
and continue on."
,"Winston Churchill"
).
quotation(
"if they give you ruled paper, write the other
way."
,"e. e. cummings"
).
quotation(
"An expert is someone who knows some of the worst
mistakes that can be made in his subject and
how to avoid them."
,"Werner Heisenberg"
).
quotation(
"Wisdom consists of knowing when to avoid perfection."
,"Horowitz' 1st Rule"
).
quotation(
"If a little knowledge is dangerous, where is the
man (sic) who has so much as to out of danger?"
," T.H. Huxley"
).
quotation(
"It's amazing how much 'mature wisdom' resembles
being too tired."
,"Long's 7th Law"
).
quotation(
"(in The House at Pooh Corner) 'Rabbit is
clever,' said Pooh thoughtfully. 'Yes,'
said Piglet, 'Rabbit's clever.' 'And he has a
Brain.' There was a long silence. 'I suppose,'
said Pooh, 'that's why he never understands
anything.'"
,"A.A. Milne"
).
quotation(
"If OO is the answer, what was the question?"
,"Tim Menzies"
).
quotation(
"Why don't my 'straw men' burn better?"
,"Tim Menzies"
).
quotation(
"The truth of a proposition has nothing to do
with its credibility and vice versa."
,"Parker's Law of Political Statements"
).
quotation(
"Fortune favors the prepared mind."
,"Blaise Pascal"
).
quotation(
"For truth can never be confirm'd enough, 
though doubts did ever sleep."
,"Pericles"
).
quotation(
"Computers in the future may weigh no more than
1.5 tons."
,"Popular Mechanics, 1949"
).
quotation("He who trains his tongue to quote the learned
sages will be known far and wide as a smartass."
,"Preston's Postulate"
).
quotation(
"And now for something completely different."
,"Monty Python"
).
quotation(
"All great truths begin as blasphemies."
,"George Bernard Shaw"
).
quotation(
"A man who has the knowledge but lacks the power
to express it is no better off than if he never
had the  ideas at all."
,"Thucydides"
).
quotation(
"I think there is a world market for about
five computers."
,"Thomas J. Watson, Chairman of IBM, 1943"
).
quotation(
"The pure and simple truth is rarely pure and 
never simple."
,"Oscar Wilde"
).


