%doing(	proj i	[d,points,]).
doing(	105,2,	[d,2,1]).
doing(	105,4,	[d,2,2]).
doing(	12,2,	[b,m,1]).
doing(	12,2,	[d,2,0,2]).
doing(	12,2,	[d,2,9,8]).
doing(	103,6,	[c,4]).
doing(	13,1,	[d,4,5]).
doing(	13,2,	[d,2,5 ]).
doing(	13,3,	[d,4,8  ]).
doing(	14,1,	[c,0]).
doing(	14,2,	[c,4]).
doing(	14,3,	[d,2,5]).                                                      
doing(	2,1,	[d,2,1,4]).
doing(	2,1,	[d,2,5,6 ]).
doing(	2,1,	[d,2,7,2]).
doing(	2,1.5,	[d,2,8,3]).
doing(	2,1.5,	[d,2,8,4]).
doing(	21,1,	[d,2,1]).
doing(	21,1,	[d,2,8]).
doing(	21,2,	[d,2,4]).
doing(	21,2,	[d,2,5]).
doing(	36,6,	[k,6,3]).
doing(	37,2,	[d,2,2]).
doing(	37,4,	[d,2,8]).
doing(	44,2,	[d,2,8,1]).
doing(	44,4,	[d,2,8,4]).
doing(	46,1,	[d,2,8,4]).
doing(	46,2,	[d,2,8,3]).
doing(	46,3,	[d,2,5]).
doing(	48,1,	[c,0]).
doing(	48,1,	[d,2,1]).
doing(	48,1,	[d,2,4]).
doing(	48,3,	[d,2,4]).
doing(	49,1,	[d,2,1]).
doing(	49,1,	[d,2,4]).
doing(	49,1,	[d,2,5  ]).
doing(	49,1,	[d,2,5 ]).
doing(	49,2,	[d,2,4]).
doing(	50,3,	[d,2,9]).
doing(	50,3,	[d,2,9]).
doing(	59,0.5,	[h,3,1]).
doing(	59,1,	[d,2,1]).
doing(	59,1,	[h,3,3]).
doing(	59,1.75,[d,2,5 ]).
doing(	59,1.75,[h,4,m]).
doing(	6,2,	[d,2,4]).
doing(	6,2,	[d,2,5]).
doing(	6,2,	[d,4,6]).
doing(	75,2,	[i,2,11]).
doing(	75,4,	[d,2,4]).
doing(	89,1,	[d,2,5 ]).
doing(	89,2,	[d,2,4]).
doing(	89,3,	[d,2,8]).
doing(	92,1,	[d,2,4]).
doing(	92,1,	[d,2,9]).
doing(	92,4,	[d,2,4]).
doing(	94,2,	[d,2,2]).
doing(	94,2,	[d,2,4]).
doing(	94,2,	[d,2,9]).
doing(	95,2,	[d,2,4]).
doing(	95,4,	[d,2,4]).
