* boolean are oneOf = [t,f].
* authors are [groups = [1],persons= [tim ='tim@menzies.com']
	      ,members= [1 = [tim]]].
* boolean are [aa,ll,bb,mm,nn,ii,jj
              ,kk,cc,dd,ee,ff,gg,hh].
* author = 1.
/* *  1 if aa then ll.
*  2 if ll then bb.
*  3 if mm then nn.
*  4 if bb then ii.
*  5 if ii then jj.
*  6 if jj then kk.
*  7 if bb then cc.
*  8 if cc then dd.
*  9 if dd then ee.
* 10 if bb then ff.
* 11 if ff then gg.
* 13 if gg then hh.
* 14 if nn then bb. */

* 1 if aa then bb.
* 2 if mm then not bb.
* 3 if bb then ee.
* 4 if bb then kk.
* 5 if not bb then not hh.












