/*

=head1 Template

Standard Prolog file structure */

/*

=head1 Header */

/*

=head2 Loads 

Load some code using "ensure_loaded". */


/*

=head2 Operators 

Change the Prolog parser using C<op/3>x. */

/*

=head2 Flags 

Index predicates (with C<index/1>)
or make some dynamic (with C<dynamic/1>)
or discontiguous (with C<discontiguous/1>)
or ...

/*

=head2  Hooks 

Change the Prolog parser using C<term_expansion/2> and
C<goal_expansion/2>. */

/*

=head2 Hacks 

We won't talk about these. Moving right along... */

/*

=head1 Body 

 Insert your applciation code here. */

/*


=head1 Footer */

/*

=head2 Start-ups 

After all the above is loaded, how do we get this stuff started. */
