Accomplishments
** General
   1. WVU commitments: retreat day Tuesday, gave a class Thursday
   2. Meet with edward Addy re WORM summary
   3. Meet with Nancy re product-line practice and testability results
   4. Invited to run the Banff KA workshop track on evaluation of KE
      methodologies
   5. The IJCAI '99 conference has approved our Empirical AI workshop
      (I'm on the programme committee)
   6. Via Bashar, found an exciting connection from abduction to Colin
      Pott's (Georgia Tech) work on methodologies for early lifecycle
      detection of and clarification of system goals

** ALIEN workbench
   1. Mapped Bashar's QC logic examples into ALIEN
   2. Work on descritisation continues (much harder than first thought)
   3. Began design for OO and state chart extensions to ALIEN

** Machine Learning of V&V
   1. With Linda Blake, found source for a machine learner

** Limits to Test
   1. Data analysed from DSTO Australia: interesting results- in certain
      cases, the length of the simulation does not effect out ability to
      test a program.
   2. "Faster Testing" paper working on 0.5 draft

Futures
** AMES visit
** PRICAI (during thanskgiving break)
** Mike Houle visit (Jan)

Concerns
** None

