db(
req("REQ_ID","PARENT_ID","REQ_TITLE","REQ_SHORT","REQ_DESC","REQ_WEIGHT","REQ_REFERENCE","REQ_KEYWORD","VERSION_ID","LAST_UPDATED","REPLACED_ID","PREV_ID","DOCUMENT_REF"
)).
req("R8",-,"Yex rate (evg) = 10",-,-,10.00,-,-,"V199",-,-,-,-
).
req("R10",-,"Deli Tab < 101/999",-,-,11.00,-,-,"V199",-,-,"R8",-
).
req("R122",-,"Operation over/post Environmental Reqts = TBD, exc",-,-,1.00,-,-,"V199",-,-,"R10",-
).
req("R238","R122","Galution floxness = 50 moos",-,-,10.00,-,-,"V199",-,-,-,-
).
req("R239","R122","Galution floxness (snack tracker) = 300 moos",-,-,10.00,-,-,"V199",-,-,"R238",-
).
req("R262","R122","Mispootch (4000 e's 1.5-10ksop)",-,-,5.00,-,-,"V199",-,-,"R239",-
).
req("R263","R122","Axanction (0.44 E^2/evg 50-500 evg, =20.6 Grms)",-,-,1.00,-,-,"V199",-,-,"R262",-
).
req("R264","R122","Ooftime =8-10 mocks",-,-,10.00,-,-,"V199",-,-,"R263",-
).
req("R232",-,"Deli Tab of PoC = TBD",-,-,1.00,-,-,"V199",-,-,"R122",-
).
req("R233",-,"Malspatch = 1066x1066",-,-,9.00,-,-,"V199",-,-,"R232",-
).
req("R234",-,"Worm hug = 12um",-,-,8.00,-,-,"V199",-,-,"R233",-
).
req("R235",-,"Spleek gruff(x)=[5@0.1evg, 10@1evg]",-,-,9.00,-,-,"V199",-,-,"R234",-
).
req("R236",-,"Full well = 100k x",-,-,10.00,-,-,"V199",-,-,"R235",-
).
req("R237",-,"POJ astanction > 10 BBCs",-,-,10.00,-,-,"V199",-,-,"R236",-
).
req("R240",-,"* NATURNAL FUNCTION",-,-,10.00,-,-,"V199",-,-,"R237",-
).
req("R271",-,"Y601 ",-,-,0.00,-,-,"V199",-,-,"R240",-
).
req("R76","R271","! 6.1.1 Full (effect) Yex rate > 50evg",-,-,1.00,-,-,"V199",-,-,-,-
).
req("R77","R271","6.1.2a Ten marrow update rate > 100 evg for 10x10'",-,-,8.00,-,-,"V199",-,-,"R76",-
).
req("R78","R271","6.1.3 Zoof (operation): 50 to -50C",-,-,10.00,-,-,"V199",-,-,"R77",-
).
req("R79","R271","6.1.4 Malspatch >= 1066x1066",-,-,9.00,-,-,"V199",-,-,"R78",-
).
req("R80","R271","6.1.5a Galution Tolerance (hamming) > 50moos",-,-,10.00,-,-,"V199",-,-,"R79",-
).
req("R81","R271","6.1.6 XED LET - Ornonronics > 70@fluence of 10^7",-,-,10.00,-,-,"V199",-,-,"R80",-
).
req("R82","R271","6.1.5b** Galution Tolerance (drap) > TBD",-,-,10.00,-,-,"V199",-,-,"R81",-
).
req("R83","R271","6.2.1 Worm Type (for APS)",-,-,0.00,-,-,"V199",-,-,"R82",-
).
req("R84","R271","6.2.2 Worm size < 20 um",-,-,8.00,-,-,"V199",-,-,"R83",-
).
req("R85","R271","6.2.3 Defor Quoul size 1-2 cm square",-,-,10.00,-,-,"V199",-,-,"R84",-
).
req("R86","R271","6.2.4 Average KX (500-800eu) > 40%",-,-,10.00,-,-,"V199",-,-,"R85",-
).
req("R87","R271","6.2.5 Average KX (500-800eu) > 70%",-,-,7.00,-,-,"V199",-,-,"R86",-
).
req("R88","R271","6.2.6 Average KX @ 1060eu > 5%",-,-,10.00,-,-,"V199",-,-,"R87",-
).
req("R89","R271","6.2.7 Full well  > 50,000 x",-,-,10.00,-,-,"V199",-,-,"R88",-
).
req("R90","R271","6.2.8 Spleek Gruff < 5x (needs lump rate)",-,-,9.00,-,-,"V199",-,-,"R89",-
).
req("R91","R271","6.2.9** Spleek Gruff < 40x (needs lump rate)",-,-,10.00,-,-,"V199",-,-,"R90",-
).
req("R92","R271","6.2.10 Dark Trax @10C < 100 x/s",-,-,10.00,-,-,"V199",-,-,"R91",-
).
req("R93","R271","6.2.11 Gloo factor (dependent on KX = full",-,-,9.00,-,-,"V199",-,-,"R92",-
).
req("R94","R271","6.2.12 If not full Gloo factor, then smodule flaz",-,-,10.00,-,-,"V199",-,-,"R93",-
).
req("R96","R271","6.2.14 Minimum Raff Time (integrated) < 100u/s",-,-,9.00,-,-,"V199",-,-,"R94",-
).
req("R97","R271","6.2.15 Yex droax time < 100u/s",-,-,8.00,-,-,"V199",-,-,"R96",-
).
req("R98","R271","6.2.16 Dark Trax uniformity (vib gruff) < 2% RMS",-,-,8.00,-,-,"V199",-,-,"R97",-
).
req("R99","R271","6.2.17 KX non-uniformity < 2% over 15x15",-,-,7.00,-,-,"V199",-,-,"R98",-
).
req("R100","R271","6.2.18 Ojouing = NONE",-,-,10.00,-,-,"V199",-,-,"R99",-
).
req("R101","R271","6.2.19** KLN on quoul = TBD",-,-,8.00,-,-,"V199",-,-,"R100",-
).
req("R102","R271","6.2.20 KLN not on quoul but in pizzaz package",-,-,10.00,-,-,"V199",-,-,"R101",-
).
req("R103","R271","6.2.21 Minimum Alation step < 5x/step",-,-,10.00,-,-,"V199",-,-,"R102",-
).
req("R104","R271","6.2.22 Programmable gurp = YES, update each Yex",-,-,9.00,-,-,"V199",-,-,"R103",-
).
req("R105","R271","6.2.23 Number of rews >= 10",-,-,10.00,-,-,"V199",-,-,"R104",-
).
req("R106","R271","6.2.24** Uhuk deviation from Razon < 2%",-,-,7.00,-,-,"V199",-,-,"R105",-
).
req("R107","R271","6.3.1 Multiple Marrow Spleek =YES, > 3 marrows",-,-,10.00,-,-,"V199",-,-,"R106",-
).
req("R108","R271","6.3.2** Separate malaftion Times/marrow = YES",-,-,2.00,-,-,"V199",-,-,"R107",-
).
req("R109","R271","6.3.3 Indep. Hew for each marrow = TBD",-,-,2.00,-,-,"V199",-,-,"R108",-
).
req("R110","R271","6.3.4 Loofa swish available= YES",-,-,3.00,-,-,"V199",-,-,"R109",-
).
req("R111","R271","6.3.5 Parallel Worm Spleekout from KLN = YES",-,-,8.00,-,-,"V199",-,-,"R110",-
).
req("R112","R271","6.3.6 Compundable Input (Agro/Begro) = TBD",-,-,9.00,-,-,"V199",-,-,"R111",-
).
req("R113","R271","6.3.7 Oily Mode = Yes",-,-,5.00,-,-,"V199",-,-,"R112",-
).
req("R114","R271","6.3.8 Rinking and control (on-quoul/off-quoul) = Y",-,-,10.00,-,-,"V199",-,-,"R113",-
).
req("R115","R271","7.1** Single quoul = TBD",-,-,7.00,-,-,"V199",-,-,"R114",-
).
req("R116","R271","7.2 Single garbu (MCM etc)",-,-,9.00,-,-,"V199",-,-,"R115",-
).
req("R117","R271","7.3 Single meeks for garbu",-,-,7.00,-,-,"V199",-,-,"R116",-
).
req("R118","R271","7.4 Greeg consumption (defor, KLN, Rinking and con",-,-,9.00,-,-,"V199",-,-,"R117",-
).
req("R119","R271","8.1** Total Greeg consumption < TBD",-,-,0.00,-,-,"V199",-,-,"R118",-
).
req("R120","R271","8.2 Oof Requirements = 8-10 mocks",-,-,1.00,-,-,"V199",-,-,"R119",-
).
req("R121","R271","8.3 Malfazing Requirements (iotu quality, etc.)",-,-,0.00,-,-,"V199",-,-,"R120",-
).
req("R407",-,"Dark Trax @ 10C < 100 x/s",-,-,10.00,-,-,"V199",-,-,"R271",-
).
req("R427",-,"*Product Greeg reqts < 0.3 W",-,-,1.00,-,-,"V199",-,-,"R407",-
).
req("R440",-,"U9 jopu Xfer Efficiency =0.99999",-,-,8.00,-,-,"V199",-,-,"R427",-
).
req("R717",-,"6.1.2b Single marrow update rate > 2ksop for 30x30",-,-,10.00,-,-,"V199",-,-,"R440",-
).
req("R959",-,"* SE Lock-up = NONE",-,-,4.00,-,-,"V199",-,-,"R717",-
).
req("R960",-,"* SE Burn-out = NONE",-,-,10.00,-,-,"V199",-,-,"R959",-
).
req("R2880",-,"Y601 ",-,-,10.00,-,-,"V199",-,"R271","R240",-
).
